baseURL = "https://iiacoban42.github.io/recipe-book/"
canonifyURLs = true
languageCode = "en-us"
title = "Tasty Bytes 🔥"
theme = "recipes"

[params]
  author = "iiacoban42"
  description = "Tasty Bytes"